export const RABBITMQ_CONNECTION_TOKEN = Symbol('RABBITMQ_CONNECTION_TOKEN');
export const RABBITMQ_CONNECTION_OPTIONS_TOKEN = Symbol('RABBITMQ_CONNECTION_OPTIONS_TOKEN');

export const RABBITMQ_SUBSCRIBE_EXCHANGE_OPTIONS_TOKEN = Symbol('RABBITMQ_SUBSCRIBE_EXCHANGE_OPTIONS_TOKEN');
export const RABBITMQ_SUBSCRIBE_QUEUE_OPTIONS_TOKEN = Symbol('RABBITMQ_SUBSCRIBE_QUEUE_OPTIONS_TOKEN');
export const RABBITMQ_SUBSCRIBE_EXCHANGE_ROUTINGKEY_TOKEN = Symbol('RABBITMQ_SUBSCRIBE_EXCHANGE_ROUTINGKEY_TOKEN');
